### ISSUE TITLE
Complete implementation release plan?

### ISSUE THREAD

**Issue by HarveyGuo960817** [r06942054/NOTE-RCNN#1]
Hello, I read your paper and wonder know when you will plan to release the complete implementation. Thank you for your work and look forward to your reply.

**Comment by r06942054** [comment]
Hi,
I appreciate your comment, but I am not the author of NOTE-RCNN.
To finish my master thesis, I only implemented the structure of NOTE-RCNN and didn't reproduce the results of the experiments in the paper.

As far as I know, the author did not release the source code

**Comment by HarveyGuo960817** [comment]
Oh, thank you !
